/**
 * Mock data for tech stack visualization tests
 */

import type { TechLayer, Technology } from '../../src/types';

export const mockTechLayers: TechLayer[] = [
  {
    id: 'runtime',
    name: 'Runtime',
    description: 'Node.js 20+, TypeScript 5.3+',
    order: 0,
    color: '#339933',
    technologies: [
      {
        id: 'nodejs',
        name: 'Node.js',
        version: '20+',
        purpose: 'JavaScript runtime environment',
        icon: 'nodejs',
        docUrl: 'https://nodejs.org',
        category: 'runtime',
      },
      {
        id: 'typescript',
        name: 'TypeScript',
        version: '5.3+',
        purpose: 'Type-safe JavaScript superset',
        icon: 'typescript',
        docUrl: 'https://typescriptlang.org',
        category: 'language',
      },
    ],
  },
  {
    id: 'core-framework',
    name: 'Core Framework',
    description: 'agentic-flow, RuVector Intelligence',
    order: 1,
    color: '#3b82f6',
    technologies: [
      {
        id: 'agentic-flow',
        name: 'agentic-flow',
        version: '1.0',
        purpose: 'Multi-agent coordination framework',
        icon: 'agentic',
        docUrl: '#',
        category: 'framework',
        dependencies: ['nodejs'],
      },
      {
        id: 'ruvector',
        name: 'RuVector',
        version: '1.0',
        purpose: 'Intelligence system with SONA, MoE, EWC++',
        icon: 'neural',
        docUrl: '#',
        category: 'intelligence',
        dependencies: ['nodejs', 'typescript'],
      },
    ],
  },
  {
    id: 'memory',
    name: 'Memory',
    description: 'AgentDB, HNSW, SQLite',
    order: 2,
    color: '#22c55e',
    technologies: [
      {
        id: 'agentdb',
        name: 'AgentDB',
        version: '1.0',
        purpose: 'Agent-optimized database with vector support',
        icon: 'database',
        docUrl: '#',
        category: 'database',
        dependencies: ['sqlite'],
      },
      {
        id: 'hnsw',
        name: 'HNSW',
        version: '1.0',
        purpose: '150x-12,500x faster vector search',
        icon: 'vector',
        docUrl: '#',
        category: 'algorithm',
      },
      {
        id: 'sqlite',
        name: 'SQLite',
        version: '3.40+',
        purpose: 'Embedded relational database',
        icon: 'sqlite',
        docUrl: 'https://sqlite.org',
        category: 'database',
      },
    ],
  },
  {
    id: 'security',
    name: 'Security',
    description: 'Zod, bcrypt, Helmet',
    order: 3,
    color: '#ef4444',
    technologies: [
      {
        id: 'zod',
        name: 'Zod',
        version: '3.22+',
        purpose: 'TypeScript-first schema validation',
        icon: 'zod',
        docUrl: 'https://zod.dev',
        category: 'validation',
      },
      {
        id: 'bcrypt',
        name: 'bcrypt',
        version: '5+',
        purpose: 'Password hashing',
        icon: 'security',
        docUrl: '#',
        category: 'crypto',
      },
      {
        id: 'helmet',
        name: 'Helmet',
        version: '7+',
        purpose: 'HTTP security headers',
        icon: 'helmet',
        docUrl: 'https://helmetjs.github.io',
        category: 'http-security',
      },
    ],
  },
  {
    id: 'communication',
    name: 'Communication',
    description: 'MCP, WebSocket, Express',
    order: 4,
    color: '#8b5cf6',
    technologies: [
      {
        id: 'mcp',
        name: 'MCP',
        version: '1.0',
        purpose: 'Model Context Protocol for tool integration',
        icon: 'mcp',
        docUrl: '#',
        category: 'protocol',
      },
      {
        id: 'websocket',
        name: 'WebSocket',
        version: 'RFC 6455',
        purpose: 'Real-time bidirectional communication',
        icon: 'websocket',
        docUrl: '#',
        category: 'protocol',
      },
      {
        id: 'express',
        name: 'Express',
        version: '4.18+',
        purpose: 'HTTP server framework',
        icon: 'express',
        docUrl: 'https://expressjs.com',
        category: 'http',
        dependencies: ['nodejs'],
      },
    ],
  },
  {
    id: 'intelligence',
    name: 'Intelligence',
    description: 'SONA, MoE, EWC++',
    order: 5,
    color: '#f59e0b',
    technologies: [
      {
        id: 'sona',
        name: 'SONA',
        version: '1.0',
        purpose: 'Self-Optimizing Neural Architecture (<0.05ms adaptation)',
        icon: 'neural',
        docUrl: '#',
        category: 'neural',
      },
      {
        id: 'moe',
        name: 'MoE',
        version: '1.0',
        purpose: 'Mixture of Experts for specialized routing',
        icon: 'moe',
        docUrl: '#',
        category: 'neural',
      },
      {
        id: 'ewc',
        name: 'EWC++',
        version: '1.0',
        purpose: 'Elastic Weight Consolidation (prevents forgetting)',
        icon: 'ewc',
        docUrl: '#',
        category: 'neural',
      },
      {
        id: 'flash-attention',
        name: 'Flash Attention',
        version: '2.0',
        purpose: '2.49x-7.47x speedup',
        icon: 'attention',
        docUrl: '#',
        category: 'neural',
      },
    ],
  },
];

export const mockTechStackData = {
  version: '3.0.0-alpha',
  layers: mockTechLayers,
  dependencies: [
    { from: 'agentic-flow', to: 'nodejs' },
    { from: 'ruvector', to: 'nodejs' },
    { from: 'ruvector', to: 'typescript' },
    { from: 'agentdb', to: 'sqlite' },
    { from: 'express', to: 'nodejs' },
  ],
};
